CREATE TABLE `TICKETS` (
	`TICKET_ID` varchar NOT NULL AUTO_INCREMENT,
	`SCHEDULE_ID` varchar,
	`FARE` INT,
	`USER_ID` INT NOT NULL,
	`NO_SEATS` INT NOT NULL,
	PRIMARY KEY (`TICKET_ID`)
);

CREATE TABLE `BUSES` (
	`BUS_NO` INT(11) NOT NULL AUTO_INCREMENT,
	`BUS_NAME` varchar(20),
	`TYPE` varchar(25),
	`TOTAL_SEATS` INT NOT NULL,
	`AVAIL_SEATS` INT NOT NULL,
	PRIMARY KEY (`BUS_NO`)
);

CREATE TABLE `PAYMENT` (
	`PAYMENT_ID` varchar(3) NOT NULL AUTO_INCREMENT,
	`TICKET_ID` varchar,
	`BD_ID` INT(11) NOT NULL,
	`DISCOINT_ID` varchar NOT NULL,
	PRIMARY KEY (`PAYMENT_ID`)
);

CREATE TABLE `DISCOUNTS` (
	`DISCOUNT_ID` varchar NOT NULL AUTO_INCREMENT,
	`DISCOUNT_AMOUNT` INT(11) NOT NULL,
	PRIMARY KEY (`DISCOUNT_ID`)
);

CREATE TABLE `SCHDULE` (
	`SHEDULE_ID` DATE NOT NULL,
	`TRAVEL_DATE` DATE,
	`SOURCE` DATE,
	`DESTINATION` varchar,
	`BUS_NO` INT,
	`DURATION` INT,
	PRIMARY KEY (`SHEDULE_ID`)
);

CREATE TABLE `USERS` (
	`USER_ID` INT NOT NULL AUTO_INCREMENT,
	`NAME` varchar(255) NOT NULL AUTO_INCREMENT,
	`ADDRESS` varchar NOT NULL AUTO_INCREMENT,
	`PHNO` INT NOT NULL AUTO_INCREMENT,
	`EMAILID` varchar NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`USER_ID`)
);

CREATE TABLE `CANCELATION` (
	`CANCELATION_ID` BINARY NOT NULL,
	`TICKET_ID` varchar NOT NULL,
	`BD_ID` varchar,
	PRIMARY KEY (`CANCELATION_ID`)
);

CREATE TABLE `BOOKINDETAILS` (
	`BD_ID` varchar NOT NULL,
	`ACC_NO` INT NOT NULL,
	`NAME` varchar NOT NULL,
	`USER_ID` INT NOT NULL,
	PRIMARY KEY (`BD_ID`)
);

ALTER TABLE `TICKETS` ADD CONSTRAINT `TICKETS_fk0` FOREIGN KEY (`SCHEDULE_ID`) REFERENCES `SCHDULE`(`SHEDULE_ID`);

ALTER TABLE `TICKETS` ADD CONSTRAINT `TICKETS_fk1` FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`USER_ID`);

ALTER TABLE `PAYMENT` ADD CONSTRAINT `PAYMENT_fk0` FOREIGN KEY (`TICKET_ID`) REFERENCES `TICKETS`(`TICKET_ID`);

ALTER TABLE `PAYMENT` ADD CONSTRAINT `PAYMENT_fk1` FOREIGN KEY (`BD_ID`) REFERENCES `BOOKINDETAILS`(`BD_ID`);

ALTER TABLE `PAYMENT` ADD CONSTRAINT `PAYMENT_fk2` FOREIGN KEY (`DISCOINT_ID`) REFERENCES `DISCOUNTS`(`DISCOUNT_ID`);

ALTER TABLE `SCHDULE` ADD CONSTRAINT `SCHDULE_fk0` FOREIGN KEY (`BUS_NO`) REFERENCES `BUSES`(`BUS_NO`);

ALTER TABLE `CANCELATION` ADD CONSTRAINT `CANCELATION_fk0` FOREIGN KEY (`TICKET_ID`) REFERENCES `TICKETS`(`TICKET_ID`);

ALTER TABLE `CANCELATION` ADD CONSTRAINT `CANCELATION_fk1` FOREIGN KEY (`BD_ID`) REFERENCES `BOOKINDETAILS`(`BD_ID`);

ALTER TABLE `BOOKINDETAILS` ADD CONSTRAINT `BOOKINDETAILS_fk0` FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`USER_ID`);
